name: Deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: voice-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: voice-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build and Push Backend Image
      run: |
        docker build -t gcr.io/$PROJECT_ID/voice-backend:$GITHUB_SHA ./backend
        docker push gcr.io/$PROJECT_ID/voice-backend:$GITHUB_SHA

    - name: Build and Push Frontend Image
      run: |
        docker build -t gcr.io/$PROJECT_ID/voice-frontend:$GITHUB_SHA ./frontend
        docker push gcr.io/$PROJECT_ID/voice-frontend:$GITHUB_SHA

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Deploy to GKE
      run: |
        # Update backend deployment
        kubectl set image deployment/voice-backend voice-backend=gcr.io/$PROJECT_ID/voice-backend:$GITHUB_SHA -n voice-app
        
        # Update frontend deployment
        kubectl set image deployment/voice-frontend voice-frontend=gcr.io/$PROJECT_ID/voice-frontend:$GITHUB_SHA -n voice-app
        
        # Wait for rollout to complete
        kubectl rollout status deployment/voice-backend -n voice-app
        kubectl rollout status deployment/voice-frontend -n voice-app

    - name: Verify deployment
      run: |
        kubectl get pods -n voice-app
        kubectl get services -n voice-app